spring.application.name=cloudtestapp
spring.datasource.url=jdbc:mysql://localhost:3306/cloudtestapp
spring.datasource.username=root
spring.datasource.password=Spongekid05
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true